theme: jekyll-theme-minimal
title: Windows set-up automation
description: Set-up your Windows environment from a fresh installation, with just a line of code!
logo: theme-logo.png
favicon: theme-logo.ico
show_downloads: false
# google_analytics: 